void draw_chart(int x,
                int y,
                int width,
                int height,
                const char *title,
                const char *yaxislabel,
                int xmin,
                int xmax,
                int ymin,
                int ymax,
                int *xdata,
                int *ydata,
                int points);

void draw_chart_fit(int x,
                    int y,
                    int width,
                    int height,
                    const char *title,
                    const char *yaxislabel,
                    int *xdata,
                    int *ydata,
                    int points);
